URLShortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('url_shorts.urls')),
]

url_shorts/urls.py
from django.urls import path
from . import views

app_name = "url_shorts"

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:url_hash>', views.go, name='go'),
    path('shorten', views.shorten, name='shorten'),
]

url_shorts/models.py
from django.db import models


# Create your models here.
class Urls(models.Model):
    """Store URLS and its Shortened version"""
    url = models.TextField(max_length=10000, unique=True, null=False)
    uuid = models.TextField(max_length=10, unique=True, null=False)


class Input(models.Model):
    url = models.TextField(max_length=10000, unique=True, null=False)

url_shorts/forms.py
from django.forms import *
from url_shorts.models import Input


class InputForm(ModelForm):
    url = CharField(max_length=10000)

    class Meta:
        model = Input
        fields = ['url']
        labels = {'text': ''}

url_shorts/views.py
from django.shortcuts import render, redirect
import uuid
from django.http import Http404
import url_shorts
from url_shorts.models import Input, Urls
from .forms import InputForm


# Create your views here.
def index(request):

    context = {}
    local_site = '127.0.0.1:8000/'
    site = 'url-short2.herokuapp.com/'

    # return blank form if its a GET or other request
    if request.method != 'POST':
        form = InputForm()
        context['form'] = form
        return render(request, 'index.html', context)
    # if its a POST, process data
    else:
        form = InputForm(data=request.POST)
        url_info = request.POST['url']
        print('url info: ' + url_info)

        # check if url already exists
        if Input.objects.filter(url=url_info).exists():
            urls_obj = Urls.objects.get(url=url_info)
            print('exists - uuid: ' + urls_obj.uuid)
            context['data'] = site + urls_obj.uuid

        # if url does not exist save it if valid
        elif form.is_valid():
            print('is valid')
            uid = str(uuid.uuid4())[:5]
            new_url = Urls(url=url_info, uuid=uid)
            new_url.save()
            form.save()
            context['data'] = site + uid

        else:
            print('URL is not valid')

    context['form'] = form
    return render(request, 'index.html', context)


def is_website(url: str) -> bool:
    website_regex_pattern = r"^(https?\:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})(\/[\w]*)*$"
    pass


def shorten(request):
    pass


def go(request, url_hash):
    print('request.method: ' + request.method)  # has to be GET
    print('url_hash: ' + url_hash)
    try:
        url_details = Urls.objects.get(uuid=url_hash)
    except url_shorts.models.Urls.DoesNotExist:
        msg = "Page Not Found"
        raise Http404(msg)
    return redirect('http://' + url_details.url)

templates/base.html
{% load bootstrap4 %}
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>Home - Brand</title>
</head>

<body>
    <nav class="navbar navbar-light navbar-expand bg-light navigation-clean">
        <div class="container"><a class="navbar-brand" href="#">URL Shortened</a><button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggler"></button></div>
    </nav>
</body>

</html>
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}{% endblock content %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>URL Short</title>
</head>
<body>
    {% extends "base.html" %}
    {% block content %}
    <header class="masthead text-center">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <h1 class="mb-5">Shorten your URL here!</h1>
            </div>
            <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
                <form method="post" action="{% url 'url_shorts:index' %}" class="form">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-12 col-md-9 mb-2 mb-md-0">
                            <input class="form-control form-control-lg" type="text" name="url" id="url" placeholder="Enter your URL..." />
                        </div>
                        <div class="col-12 col-md-3">
                            <button class="btn btn-primary btn-block btn-lg" type="submit">Shorten</button>
                        </div>
                    </div>
                </form>
                <div>
                    {% if data %}
                        <strong id="data">{{data}}</strong>
                    {% else %}
                        <p id="no_link">your new link will appear here</p>
                    {% endif %}
                    <button class="btn btn-primary btn-block btn-lg" onclick="copy('#data');">Copy</button>
                    <script type="text/javascript" charset="utf-8">
                        function copy(element) {
                          var $temp = $("<input>");
                          $("body").append($temp);
                          $temp.val($(element).text()).select();
                          document.execCommand("copy");
                          $temp.remove();
                        }
                    </script>
                </div>
            </div>
        </div>
    </div>
    </header>
    {% endblock content %}
</body>
</html>

templates/old_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>URL Short</title>
</head>
<body>
    {% extends "base.html" %}
    {% block content %}
    <form method="post" action="{% url 'url_shorts:index' %}" class="form">
        {% csrf_token %}
        <input type="text" name="url" id="url" placeholder="Enter URL">
        <button type="submit" class="btn btn-primary">Shorten</button>
    </form>
    <div>
        {% if data %}
            <p id="data">{{data}}</p>
        {% else %}
            <p id="no_link">link</p>
        {% endif %}
        <button class="btn btn-primary" onclick="copy('#data');">Copy</button>
        <script type="text/javascript" charset="utf-8">
            function copy(element) {
              var $temp = $("<input>");
              $("body").append($temp);
              $temp.val($(element).text()).select();
              document.execCommand("copy");
              $temp.remove();
            }
        </script>
    </div>
    {% endblock content %}
</body>
</html>